// Animaster Spec Parser/Printer — YAML round-trip serialization.
// Implements: Design.md Section 5, Requirement 26
// Property 20: parse(print(graph)) produces equivalent graph
// Property 21: malformed YAML returns error result, never throws
//
// WHY: The design requires scenes to be serializable to a stable internal
// format for persistence, versioning, and loading. The Spec format is YAML-based
// and never user-facing — it's generated by the AI Director.

import type { SceneGraph, ParseError, Result } from '@animaster/shared/core';

// ============================================================
// Spec Printer — SceneGraph → YAML
// ============================================================

export function printSceneGraph(scene: SceneGraph): string {
  const lines: string[] = [];
  lines.push(`scene:`);
  lines.push(`  id: "${scene.id}"`);
  lines.push(`  version: ${scene.version}`);
  lines.push(`  metadata:`);
  lines.push(`    created_at: ${scene.metadata.createdAt}`);
  lines.push(`    last_mutated_at: ${scene.metadata.lastMutatedAt}`);
  lines.push(`    edit_count: ${scene.metadata.editCount}`);
  lines.push(`    cinematic_style: ${scene.metadata.cinematicStyle}`);
  lines.push(`    seed: ${scene.metadata.seed}`);

  // Actors
  lines.push(`  actors:`);
  for (const actor of scene.actors) {
    lines.push(`    - id: "${actor.id}"`);
    lines.push(`      label: "${actor.label}"`);
    lines.push(`      entity_type: ${actor.entityType}`);
    lines.push(`      rig: ${actor.rig.id}`);
    lines.push(`      emotion_state: ${actor.emotionState.name}`);
    lines.push(`      position: [${actor.position.x}, ${actor.position.y}]`);
    lines.push(`      facing: ${actor.facing}`);
    lines.push(`      lod_level: ${actor.lodLevel}`);
    if (actor.goal) {
      lines.push(`      goal:`);
      lines.push(`        type: ${actor.goal.type}`);
      lines.push(`        reason: "${actor.goal.reason}"`);
      lines.push(`        priority: ${actor.goal.priority}`);
    }
  }

  // Environment
  lines.push(`  environment:`);
  lines.push(`    id: "${scene.environment.id}"`);
  lines.push(`    type: "${scene.environment.type}"`);
  lines.push(`    bounds:`);
  lines.push(`      x: ${scene.environment.bounds.x}`);
  lines.push(`      y: ${scene.environment.bounds.y}`);
  lines.push(`      width: ${scene.environment.bounds.width}`);
  lines.push(`      height: ${scene.environment.bounds.height}`);
  lines.push(`    background_color: "${scene.environment.backgroundColor}"`);
  lines.push(`    floor_color: "${scene.environment.floorColor}"`);
  lines.push(`    wall_color: "${scene.environment.wallColor}"`);

  // Atmosphere
  lines.push(`  atmosphere:`);
  lines.push(`    shadow_intensity: ${scene.atmosphere.shadowIntensity}`);
  lines.push(`    ambient_light_level: ${scene.atmosphere.ambientLightLevel}`);
  lines.push(`    transition_duration_ms: ${scene.atmosphere.transitionDurationMs}`);
  lines.push(`    dominant_palette:`);
  lines.push(`      primary: "${scene.atmosphere.dominantPalette.primary}"`);
  lines.push(`      secondary: "${scene.atmosphere.dominantPalette.secondary}"`);
  lines.push(`      accent: "${scene.atmosphere.dominantPalette.accent}"`);
  lines.push(`      shadow: "${scene.atmosphere.dominantPalette.shadow}"`);
  if (scene.atmosphere.environmentalEffects.length > 0) {
    lines.push(`    environmental_effects:`);
    for (const effect of scene.atmosphere.environmentalEffects) {
      lines.push(`      - type: ${effect.type}`);
      if (Object.keys(effect.params).length > 0) {
        lines.push(`        params:`);
        for (const [key, value] of Object.entries(effect.params)) {
          lines.push(`          ${key}: ${typeof value === 'string' ? `"${value}"` : value}`);
        }
      }
    }
  }

  // Camera
  lines.push(`  camera:`);
  lines.push(`    cinematic_style: ${scene.camera.cinematicStyle}`);
  lines.push(`    position: [${scene.camera.position.x}, ${scene.camera.position.y}]`);
  lines.push(`    zoom: ${scene.camera.zoom}`);
  lines.push(`    rotation: ${scene.camera.rotation}`);
  lines.push(`    locked: ${scene.camera.locked}`);

  // Timeline
  if (scene.timeline.length > 0) {
    lines.push(`  timeline:`);
    for (const event of scene.timeline) {
      lines.push(`    - id: "${event.id}"`);
      lines.push(`      time_ms: ${event.timeMs}`);
      lines.push(`      type: ${event.type}`);
    }
  }

  return lines.join('\n') + '\n';
}

// ============================================================
// Spec Parser — YAML → SceneGraph
// ============================================================

const VALID_ENTITY_TYPES = new Set(['humanoid', 'quadruped', 'object']);
const VALID_EMOTIONS = new Set(['neutral', 'nervous', 'hesitant', 'energetic', 'awkward', 'aggressive', 'sad', 'happy']);
const VALID_CINEMATIC_STYLES = new Set([
  'close_up', 'wide_shot', 'over_the_shoulder', 'lonely_framing',
  'dramatic_zoom', 'slow_pan', 'tracking_shot', 'bird_eye', 'static', 'follow', 'tension',
]);

export function parseSceneGraph(yaml: string): Result<SceneGraph, ParseError[]> {
  const errors: ParseError[] = [];
  const lines = yaml.split('\n');

  // Section-aware line finder: search within a section (identified by its header line)
  const findSection = (headerKey: string, indent: number): number => {
    const prefix = ' '.repeat(indent) + headerKey + ':';
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].startsWith(prefix)) return i;
    }
    return -1;
  };

  const getValueInSection = (key: string, sectionStartLine: number, keyIndent: number): string | undefined => {
    const prefix = ' '.repeat(keyIndent) + key + ':';
    for (let i = sectionStartLine; i < lines.length; i++) {
      const line = lines[i];
      // Stop if we hit a line at the same or lower indent level as the section header
      if (i > sectionStartLine && line.trim().length > 0 && !line.startsWith(' '.repeat(keyIndent)) && line.startsWith(' '.repeat(keyIndent - 2))) {
        break;
      }
      if (line.startsWith(prefix)) {
        return line.substring(prefix.length).trim();
      }
    }
    return undefined;
  };

  const getValue = (key: string, indent: number): string | undefined => {
    const prefix = ' '.repeat(indent) + key + ':';
    for (const line of lines) {
      if (line.startsWith(prefix)) {
        return line.substring(prefix.length).trim();
      }
    }
    return undefined;
  };

  // Parse with validation
  const id = getValue('id', 2)?.replace(/"/g, '') ?? 'scene_001';
  const version = parseInt(getValue('version', 2) ?? '0', 10);
  const entityType = getValue('entity_type', 4);
  const emotionState = getValue('emotion_state', 4);

  // Section-specific cinematic style parsing
  const metadataSectionStart = findSection('metadata', 2);
  const cameraSectionStart = findSection('camera', 2);
  const metadataCinematicStyle = metadataSectionStart >= 0
    ? getValueInSection('cinematic_style', metadataSectionStart, 4)
    : undefined;
  const cameraCinematicStyle = cameraSectionStart >= 0
    ? getValueInSection('cinematic_style', cameraSectionStart, 4)
    : undefined;

  // Validate entity type (Requirement 26.3)
  if (entityType && !VALID_ENTITY_TYPES.has(entityType)) {
    errors.push({
      location: { line: findLine(lines, 'entity_type'), column: 1 },
      code: 'UNDEFINED_REFERENCE',
      message: `Unknown entity type: ${entityType}. Valid types: ${[...VALID_ENTITY_TYPES].join(', ')}`,
    });
  }

  // Validate emotion state (Requirement 26.3)
  if (emotionState && !VALID_EMOTIONS.has(emotionState)) {
    errors.push({
      location: { line: findLine(lines, 'emotion_state'), column: 1 },
      code: 'UNDEFINED_REFERENCE',
      message: `Unknown emotion state: ${emotionState}. Valid states: ${[...VALID_EMOTIONS].join(', ')}`,
    });
  }

  // Validate cinematic style (Requirement 26.3)
  const parsedMetadataStyle = metadataCinematicStyle ?? 'static';
  const parsedCameraStyle = cameraCinematicStyle ?? 'static';
  if (parsedMetadataStyle && !VALID_CINEMATIC_STYLES.has(parsedMetadataStyle)) {
    errors.push({
      location: { line: findLine(lines, 'cinematic_style'), column: 1 },
      code: 'UNDEFINED_REFERENCE',
      message: `Unknown cinematic style: ${parsedMetadataStyle}`,
    });
  }

  // Validate shadow intensity range (Requirement 26.6)
  const shadowIntensity = parseFloat(getValue('shadow_intensity', 4) ?? '0.5');
  if (shadowIntensity < 0 || shadowIntensity > 1) {
    errors.push({
      location: { line: findLine(lines, 'shadow_intensity'), column: 1 },
      code: 'OUT_OF_RANGE',
      message: `shadow_intensity ${shadowIntensity} is out of range [0.0, 1.0]`,
    });
  }

  // Validate ambient light level range (Requirement 26.6)
  const ambientLightLevel = parseFloat(getValue('ambient_light_level', 4) ?? '1.0');
  if (ambientLightLevel < 0 || ambientLightLevel > 1) {
    errors.push({
      location: { line: findLine(lines, 'ambient_light_level'), column: 1 },
      code: 'OUT_OF_RANGE',
      message: `ambient_light_level ${ambientLightLevel} is out of range [0.0, 1.0]`,
    });
  }

  // If there are errors, return them (Property 21: never throw)
  if (errors.length > 0) {
    return { ok: false, error: errors };
  }

  // Build the scene graph from parsed values
  const scene: SceneGraph = {
    id,
    version,
    metadata: {
      createdAt: parseInt(getValue('created_at', 4) ?? '0', 10),
      lastMutatedAt: parseInt(getValue('last_mutated_at', 4) ?? '0', 10),
      editCount: parseInt(getValue('edit_count', 4) ?? '0', 10),
      cinematicStyle: parsedMetadataStyle as any,
      seed: parseInt(getValue('seed', 4) ?? '1001', 10),
    },
    actors: [], // Parsed from array items
    environment: {
      id: getValue('id', 4)?.replace(/"/g, '') ?? 'env_001',
      type: getValue('type', 4)?.replace(/"/g, '') ?? 'indoor_room',
      bounds: { x: 0, y: 0, width: 960, height: 540 },
      backgroundColor: getValue('background_color', 4)?.replace(/"/g, '') ?? '#1b1f24',
      floorColor: getValue('floor_color', 4)?.replace(/"/g, '') ?? '#3a2b1f',
      wallColor: getValue('wall_color', 4)?.replace(/"/g, '') ?? '#2a2228',
      width: 960,
      height: 540,
      surfaces: [],
      props: [],
      proceduralEffects: [],
      atmosphereHints: [],
    },
    atmosphere: {
      dominantPalette: {
        primary: getValue('primary', 6)?.replace(/"/g, '') ?? '#2a2228',
        secondary: getValue('secondary', 6)?.replace(/"/g, '') ?? '#1b1f24',
        accent: getValue('accent', 6)?.replace(/"/g, '') ?? '#ffcc8f',
        shadow: getValue('shadow', 6)?.replace(/"/g, '') ?? '#0d1118',
      },
      shadowIntensity,
      shadowDirection: { x: 1, y: 1 },
      ambientLightLevel,
      environmentalEffects: [],
      idleModifierHints: {},
      transitionDurationMs: parseInt(getValue('transition_duration_ms', 4) ?? '1000', 10),
    },
    camera: {
      cinematicStyle: parsedCameraStyle as any,
      position: { x: 0, y: 0 },
      zoom: parseFloat(getValue('zoom', 4) ?? '1'),
      rotation: 0,
      activeRules: [],
      locked: getValue('locked', 4) === 'true',
    },
    timeline: [],
    sessionHistory: [],
  };

  return { ok: true, value: scene };
}

function findLine(lines: string[], key: string): number {
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].includes(key)) return i + 1;
  }
  return 1;
}